number1=8
number2=9
number3=12
#calculated sum
sum=number1+number2+number3
print("sum:",sum)

#calculated diffrence
diffrence=number1-number2-number3
print("difference:",diffrence)

#calculated product
product=number1*number2*number3
print("product:",product)

#calculated average
average=(number1+number2+number3) /3
print("average:",average)

#area of triangle
breadth=5
height=7
area=0.5*breadth*height
print("triangle area",area)
#area of square
side=5
area=side*side
print("square area",area)
#area of circle
pi=3.18
radius=6
area=pi*radius*radius
print("circle area",area)
#rectangle area
length=11
width=9
area=length*width
print("rectangle area")
